# Generated by Django 4.2.2 on 2023-06-22 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30, null=True)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30, null=True)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('comuna', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('XV', 'Region de Arica y Parinacota'), ('I', 'Region de Tarapaca'), ('II', 'Region de Antofagasta'), ('III', 'Region de Atacama'), ('IV', 'Region de Coquimbo'), ('V', 'Region de Valparaiso'), ('RM', 'Region de Metropolitana'), ('VI', 'Region del Libertador General Bernardo O´Higgins'), ('VII', 'Region del Maule'), ('XVI', 'Region del Ñuble'), ('VIII', 'Region del Biobio'), ('IX', 'Region de La Araucania'), ('XIV', 'Region de Los Rios'), ('X', 'Region de Los Lagos'), ('XI', 'Region de Aysen del General Carlos Ibañez del Campo'), ('XII', 'Region de Magallanes y de la Antartica Chilena')], max_length=4)),
                ('ciudad', models.CharField(max_length=30)),
                ('referencia', models.CharField(max_length=250, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('id_clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(choices=[('1', 'Efectivo'), ('2', 'Transferencia'), ('3', 'Crédito'), ('4', 'Debito'), ('5', 'PayPal'), ('6', 'Mach')], default=3, max_length=4)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('idcliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idproducto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('mediopedido', models.CharField(choices=[(1, 'Telefono'), (2, 'Email'), (3, 'Web')], default='3', max_length=4)),
                ('deleted', models.BooleanField(default=False)),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.direccion'),
        ),
    ]
