# Generated by Django 4.2.2 on 2023-06-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
