# Generated by Django 4.2.2 on 2023-06-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='idpedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.pedido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.clasificacion'),
        ),
    ]
