# Generated by Django 4.2.2 on 2023-07-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(default='no_encontrado.png', upload_to='medios'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Preparación', 'En Preparación'), ('En Despacho', 'En Despacho'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=15),
        ),
    ]
