# Generated by Django 4.2.2 on 2023-06-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='mediopedido',
            field=models.CharField(choices=[('Telefono', 'Telefono'), ('E-mail', 'E-mail'), ('Web', 'Web')], default='Web', max_length=15),
        ),
    ]
