# Generated by Django 4.2.2 on 2023-06-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='idproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.producto'),
        ),
    ]
