# Generated by Django 4.2.2 on 2023-07-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_detallepedido_idpedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='modificable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True, verbose_name='email'),
        ),
    ]
