# Generated by Django 4.2.2 on 2023-06-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_detallepedido_idproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ManyToManyField(to='app_1.direccion'),
        ),
    ]
