# Generated by Django 4.2.2 on 2023-06-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_detallepedido_mediopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='idpedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='mediopedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_detallepedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_1.detallepedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mediopedido',
            field=models.CharField(choices=[('Telefono', 'Telefono'), ('E-mail', 'E-mail'), ('Web', 'Web')], default='Web', max_length=15),
        ),
    ]
