# Generated by Django 4.2.2 on 2023-06-21 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_cliente_telefono_alter_direccion_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idproducto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('mediopedido', models.CharField(choices=[(1, 'Telefono'), (2, 'Email'), (3, 'Web')], default='3', max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pedidos',
        ),
        migrations.AddField(
            model_name='metodopago',
            name='metodo_pago',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'Transferencia'), ('3', 'Crédito'), ('4', 'Debito'), ('5', 'PayPal'), ('6', 'Mach')], default=3, max_length=4),
        ),
        migrations.AddField(
            model_name='pedido',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idcliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago_pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.metodopago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_detallepedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.detallepedido'),
        ),
    ]
