# Generated by Django 4.2.2 on 2023-07-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_producto_descripcion_producto_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(default='medios/not-found.jpg', upload_to='medios'),
        ),
    ]
