# Generated by Django 4.2.2 on 2023-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_remove_cliente_direccion_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'En Preparación'), ('3', 'En Despacho'), ('4', 'Entregado')], default=3, max_length=4),
        ),
    ]
