# Generated by Django 4.2.2 on 2023-07-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_producto_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='img',
        ),
    ]
