# Generated by Django 4.2.2 on 2023-06-26 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_remove_detallepedido_idpedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_detallepedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.detallepedido'),
        ),
    ]
