# Generated by Django 4.2.2 on 2023-07-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_remove_producto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imag',
            field=models.ImageField(default='static/not-found.jpg', upload_to='static'),
        ),
    ]
