# Generated by Django 4.2.2 on 2023-07-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_producto_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imag',
            field=models.ImageField(default='medios/not-found.jpg', upload_to='medios'),
        ),
    ]
