# Generated by Django 4.2.2 on 2023-06-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
