# Generated by Django 4.2.2 on 2023-06-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_usuario_delete_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usuario',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
