# Generated by Django 4.2.2 on 2023-06-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_alter_cliente_segundo_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='mediopedido',
            field=models.CharField(choices=[('1', 'Telefono'), ('2', 'Email'), ('3', 'Web')], default='3', max_length=4),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('1', 'Efectivo'), ('2', 'Transferencia'), ('3', 'Crédito'), ('4', 'Debito'), ('5', 'PayPal'), ('6', 'Mach')], default='3', max_length=4),
        ),
    ]
