# Generated by Django 4.2.2 on 2023-07-07 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_carrito_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='idcarrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.carrito'),
        ),
    ]
