# Generated by Django 4.2.2 on 2023-06-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_alter_detallepedido_mediopedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
