# Generated by Django 4.2.2 on 2023-06-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_alter_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='NingunLugar', max_length=250),
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_total',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
