# Generated by Django 4.2.2 on 2023-06-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_cliente_direccion_pedido_precio_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=250),
        ),
    ]
