# Generated by Django 4.2.2 on 2023-06-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_remove_cliente_direccion_alter_direccion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Preparación', 'En Preparación'), ('En Despacho', 'En Despacho'), ('Entregado', 'Entregado')], default='Pendiente', max_length=15),
        ),
    ]
