# Generated by Django 4.2.2 on 2023-06-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='mediopedido',
            field=models.CharField(choices=[('Telefono', 'Telefono'), ('Email', 'Email'), ('Web', 'Web')], default='Web', max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Crédito', 'Crédito'), ('Debito', 'Debito'), ('PayPal', 'PayPal'), ('Mach', 'Mach')], default='Crédito', max_length=15),
        ),
    ]
