# Generated by Django 4.2.2 on 2023-06-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0014_perfilcliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilCliente',
        ),
    ]
